[workspace]
members = [
    ".",
    "kiss-plugin-sdk",
    "kiss-url-shortener",
]

[package]
name = "kiss-server"
version = "1.5.1"
edition = "2024"

[dependencies]
kiss-plugin-sdk = { path = "./kiss-plugin-sdk" }
kiss-url-shortener = { path = "./kiss-url-shortener" }
log = { version = "0.4.20", features = ["std"] }
ring = "0.17"
